# Use the official SonarQube image as the base image
FROM sonarqube:latest

# Copy the custom sonar.properties file to the configuration directory
COPY sonar.properties /opt/sonarqube/conf/sonar.properties
